include 'koma-core-api'
include 'koma-core-ejml'
include 'koma-core-jblas'
include 'koma-core-mtj'
include 'koma-core-js'
include 'koma-logging'
include 'koma-plotting'
include 'koma-tests'

project(":koma-core-api").projectDir = file("koma-core-api")
project(":koma-core-js").projectDir = file("koma-core/js-default")
project(":koma-core-ejml").projectDir = file("koma-core/jvm-ejml")
project(":koma-core-mtj").projectDir = file("koma-core/jvm-mtj")
project(":koma-core-jblas").projectDir = file("koma-core/jvm-jblas")